# Generated by Django 3.2.9 on 2022-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220415_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_count', models.IntegerField()),
                ('client_name', models.CharField(max_length=20)),
                ('client_surename', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_city', models.CharField(max_length=40)),
                ('client_address', models.CharField(max_length=100)),
            ],
        ),
    ]
